velib:
  outputs:
    dev:
      dataset: VELIB_TRIPS_MASTERCLASS_DBT # to change 
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/elevy/Desktop/DBT_MASTERCLASS_2025/KEYS/dbt-masterclass-2025-80429178c1aa.json # to change
      location: europe-west9 # to confirm
      method: service-account
      priority: interactive
      project: rare-result-248415 # to confirm
      threads: 1
      type: bigquery
  target: dev
