velib:
  outputs:
    dev:
      dataset: velib
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/elevy/Documents/DBT/dbt-user-creds.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-tutorial-371406
      threads: 1
      type: bigquery
  target: dev
